---
debug: 0
logging.version: 1
logging.disable_existing_loggers: False
logging.root.level: INFO
logging.formatters.simple: 
  format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
logging.handlers.console:
  level: DEBUG
  class: logging.StreamHandler
  formatter: simple
  stream: ext://sys.stdout
logging.loggers.InstaBot.handlers:
  - console
database.type: "sql"
database.path: '/app/db/{{login}}.db'
database.connection_string: 'sqlite:///{{database.path}}'
start_at_h: 0
start_at_m: 0
end_at_h: 23
end_at_m: 59
like_per_run: 50
like_followers_per_run: 20
media_max_like: 100
media_min_like: 10
follow_per_run: 5
follow_time: 604800
user_min_follow: 500
user_max_follow: 2000
unfollow_per_run: 5
unlike_per_run: 0
time_till_unlike: 604800
comments_per_day: 144
comment_list: 
  - 
    - this
    - the
    - your
  - 
    - photo
    - picture
    - pic
    - shot
    - snapshot
    - capture
    - beauty
    - image
  - 
    - is
    - are
    - looks
    - "is really"
  - 
    - great
    - super
    - good
    - wow
    - cool
    - great
    - magnificent
    - magical
    - stylish
    - beautiful
    - lovely
    - excellent
    - amazing
  - 
    - "."
    - "..."
    - "!"
    - "!!!"
  -
    - "visit https://glcass-beauty.com for more beauty!!"
tag_list: 
  - landscape
  - cityscape
  - portraiture
  - travel
  - sunrise
  - sunset
  - milkyway
  - drone
  - food
  - model
  - traveldestination
  - nature
  - model
  - street
  - candid
  - portraiture
  - streetfood
  - amg
  - girl
  - sexy
  - me
  - instagood
  - photoofitheday
  - fashion
  - beautiful
  - happy
  - cute
  - like4like
  - followme
  - selife
  - covid19
  - art
  - nature
  - smile
keywords:
  - photographer
  - videographer
  - filmmaker
  - traveler
tag_blacklist: 
  - lgbt
max_like_for_one_tag: 20
unfollow_break_min: 15
unfollow_break_max: 30
unfollow_not_following: true
unfollow_inactive: true
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_everyone: false
